### PR TITLE
Add URL Protocol "im:" to ALLOWED_URI_REGEXP of all search result display templates

### PR DESCRIPTION
**Pull request by till-llit**
This PR is supposed to fix the issue [3415](https://github.com/microsoft-search/pnp-modern-search/issues/3415) and extend the commit from @wobba https://github.com/microsoft-search/pnp-modern-search/commit/c9b01890926be4e396089ee81b4b3d6031ce72b9 to DetailsList, Persona, DocumentCard and SliderComponent

### CODE REVIEW

**Comment by wobba** [comment]
Can you refactor the regex to a shared one for all places being used?

**Comment by till-llit** [comment]
@wobba : hope this was the correct way to use a "shared place".

can i do anything to resolve the conflict? looks like my power is limited here.

**Comment by wobba** [comment]
@till-llit I get this error. Have you seen it?

```
TypeError: Method RegExp.prototype.test called on incompatible receiver /^(?:(?:(?:f|ht)tps?|mailto|file|tel|callto|im|cid|xmpp|xxx|ms-w+):|[^a-z]|[a-z+.-]+(?:[^a-z+.-:]|$))/i
    at String.test (<anonymous>)
```

**Comment by wobba** [comment]
Fixed it.. you had added the regex as a string, not a regex.

**Pull request merged**
