### PR TITLE
Introducing clear search on empty search box

### PR DESCRIPTION
**Pull request by salascz**
This PR helps to reset search results when user removes the query using backspace key (or keyboard in general) instead of using "X" button.

This issue was identified as one of pain points during user reviews on one of our apps.

New behaviour is optional - you can decide to use original or updated configuration...

image

### CODE REVIEW

**Comment by FranckyC** [comment]
Hi @salascz, looks fine but you need to update the documentation as well.

**Comment by FranckyC** [comment]
Also, please update your branch with the latest `develop` to avoid conflicts

**Comment by salascz** [comment]
I tried to rebase to develop, hope it went well...

I will check the documentation later today or tomorrow. Sorry for delay, its kind of side-project for me + first github PR greater than few lines....

**Comment by FranckyC** [comment]
It went well @salascz. Thanks for the valuable contribution 🎉

**Pull request merged**
