### PR TITLE
SPFx-upgrade-search-extensibility to v1.20.0

### PR DESCRIPTION
**Pull request by NishkalankBezawada**
SPFx-upgrade-search-extensibility to v1.20.0

I have succesfully built the project, without any errors. 

image

I was unable to upgrade search-parts as search-extensibility should need to align with @microsoft/sp-core-library@1.20.0. Hence will be creating a seperate Pull request for upgrade of search-parts. 

Thanks,
Nish

### CODE REVIEW

**Comment by wobba** [comment]
No need to update this until web parts build above 1.18.2.

**Comment by NishkalankBezawada** [comment]
> No need to update this until web parts build above 1.18.2. Already made a 1.19 version - but not of any use.

Hello @wobba,

Thanks for the update. 

But since search-parts webparts, which is using 'search-extensibility' as a package,  upgrading webparts gives as below errors, 

image


So, I thought that it would be good if we can first upgrade the 'search-extensibility' and then the webparts. 

Thanks,
Nishkalank

**Comment by NishkalankBezawada** [comment]
> No need to update this until web parts build above 1.18.2. Already made a 1.19 version - but not of any use.

Hello Mikael @wobba 

I have tested by linking search-extensibility (which is on 1.20.0) and build the search-parts with the current version (1.18.2) and search webparts are working fine. 

Below are the screenshots, 

Sample changes1


and,

image


I will now, proceed with upgrading the search-parts projects to SPFx v1.20.0

Thanks,
Nishkalank

**Comment by wobba** [comment]
I'll merge this and get a 1.20 npm package out.. hope you manage to build the web parts on 1.20 as I had an issue going above 1.18.2.

**Comment by wobba** [comment]
@NishkalankBezawada NishkalankBezawada  npm version for 1.20.0 is out so you can reference it in the web part project when you test.

**Pull request merged**
