### PR TITLE
Fixed images - resolves issue #1156

### LINKED ISSUE #1156: Images incorrectly added to scenario articles
Documentation issue with images in the scenario docs. Example:

https://microsoft-search.github.io/pnp-modern-search/scenarios/page-with-filters/
But it seems the page was having an error? :::image type="content" source="assets/page-with-filters/page-layout-with-filters.png" alt-text="Page layout with PnP Filters Web Part":::

Mentioned in #1146 

Please assign to me.

### PR DESCRIPTION
**Pull request by sympmarc**
Fixes #1156

### CODE REVIEW

**Comment by FranckyC** [comment]
Thanks @sympmarc , I'll deploy the updated documentation.

**Comment by wobba** [comment]
Changed base as it's easier to merge to main, then merge that into dev. Quicker doc deploy.

**Comment by FranckyC** [comment]
@wobba you can actually use `mkdocs gh-deploy` on any branch technically. It does not really matter. I re-target to `develop` to follow the release cycle. I'll publish the doc from here.

**Comment by FranckyC** [comment]
Oh btw thanks @sympmarc  ;)

**Comment by sympmarc** [comment]
Which branch would you prefer I do PRs against for docs?

**Comment by FranckyC** [comment]
I prefer `develop` to follow the release cycle. It also avoids potential conflicts and duplicates if the latest version is in the main branch but people start their changes from develop. We can publish from any branch anyway.

**Comment by sympmarc** [comment]
Aye, aye! I will continue to do PRs against `develop`.

Let me know what you hear about these scenarios and any others you think might be helpful. Happy to take on new issues for same.

**Comment by wobba** [comment]
@FranckyC I disagree. I think we can merge docs into main, publish right away, and merge back to develop. Allows for quicker doc updates.

* merge PR into main
* merge main down to dev right away

should keep docs in sync without conflict. At least for scenario docs which is not docs tied to new code being added.

**Pull request merged**
