### PR TITLE
Include new handlebars function

### PR DESCRIPTION
**Pull request by kachihro**
Updates include ONE new function for HandleBars.    (some spaces/formatting - auto-fix when saving in VS-CODE)

### CODE REVIEW

**Comment by wobba** [comment]
You need to update the documentation as well for this new helper.

**Comment by FranckyC** [comment]
Thanks @kachihro ! Like @wobba says, just update the doc and we are good to go

**Comment by wobba** [comment]
@kachihro can you close one of your PR's? And no need to create a new one.. you just update your branch and the PR is updated with whatever commits. I added some comments to #1873

**Comment by kachihro** [comment]
IGNORE THIS PR

**Pull request closed without merging**
