### PR TITLE
972: Refiner Grouping 

### PR DESCRIPTION
**Pull request by edarroudi**
See https://github.com/microsoft-search/pnp-modern-search/issues/972
This is just a draft for now as there might be the need for additional options, security checks ...
image
image
image
image
image

Todos:

1. Additional language resources
2. Check for possible security issues
3. Update documentation
4. Many tests / combinations
3. How to go on with the counts. Its probably impossible to correctly calculate the "advanced" mode count

**Decided to check the following 2 options in another version. Will add too much complexity right now.**
 _[optional] Allow the usage of Tokens in the advanced (and simple) fql.
 [optional] Allow user to set if Grouped labels should stay of the top of the Combobox/Checkbox_

Regarding the advanced FQL request: It works but i'm not sure if it is really correct from the syntax :)

### CODE REVIEW

**Comment by wobba** [comment]
Sorry we don't have time to properly test this for the next release, but will get it included in the v4.8 release.

**Comment by wobba** [comment]
Should we set this from draft and start to address it?

**Comment by edarroudi** [comment]
> Should we set this from draft and start to address it?

no I still have to adress some issues / optimize it. I'm thinking of switching to a rule tree control for the advanced KQL mode but I have to finish that controll here https://github.com/pnp/sp-dev-fx-property-controls/pull/456 (very soon).

Will concentrate on this PR beginning next week. Do you know when you guys will publish 4.8.0 ?

**Comment by edarroudi** [comment]
@wobba I had some time to think about it. The advanced Editor is not necessary and as it would lead to a lot of work I think we should move forward with this solution. My questions / Todos are still open - I will continue / finish the implementation once you and @FranckyC come to a conclusion or have some remarks on this - otherwise I will be investing a lot of time without knowing if you guys are actually ok with the approach. Thats why I set this now to Ready for reveiew - although it's not really 100% ready ;-)

**Comment by edarroudi** [comment]
Update 2022-11-11
I'm currently updating the handling of Grouped Filter (Labels) and testing everything. Will request a review once done (probably by monday).

**Comment by edarroudi** [comment]
I fixed some issues and tested it many times. From my perspektive it works fine. 
I don't allow refiner grouping on date type templates yet. Maybe in a future version? Don't know if i would have to check several issues there.

@FranckyC do you have some time to check / comment this?

Once I get a go I update the rest of the language files and the docs. **Thank you.**

**Comment by edarroudi** [comment]
I will add and test number fields with ranges next week. And check what has to be done for date fields

**Comment by edarroudi** [comment]
For now again in draft, will recheck this. Maybe wil start with some refactoring of the base filter code itself in another branch.

**Comment by wobba** [comment]
Should we close this one?

**Comment by edarroudi** [comment]
Yeah there is too much work left for it to work in every scenario. And those users who want to have grouped refiners can implement it through UI in the current version.

**Comment by mozilla0** [comment]
@edarroudi where did you implement this in the UI?

**Comment by MirasMNC** [comment]
> Yeah there is too much work left for it to work in every scenario. And those users who want to have grouped refiners can implement it through UI in the current version.

Hi, may I ask you how is this possible to do it via UI? Currently we are facing the same issue that end users gave us feedback about filters. It would be nice to have an option to group some filetypes and give them friendly display name. Thank you :)

**Comment by wobba** [comment]
@MirasMNC someone needs to invest developer time to create a filetype filter which works semantically and on the pure values.

**Pull request closed without merging**
