### PR TITLE
Added Swedish language support

### PR DESCRIPTION
**Pull request by olofssonlouise**
## Problem

No Swedish translation existed

## Solution

Added Swedish translation

## Other changes (e.g. bug fixes, UI tweaks, small refactors)

None.

### CODE REVIEW

**Comment by iamundsson** [comment]
Is this coming soon? Would really appreciate Swedish translation.

**Comment by wobba** [comment]
Sorry.. missed this one - and thank you :) We'll get it into the April version.

**Comment by iamundsson** [comment]
Still no April version? :) Sorry for bothering you @wobba ...

**Comment by wobba** [comment]
Time is not in abundance and you can always build a version yourself 🙂

**Pull request merged**
