### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mirkodesimone7**
Hi,
please, could you pull the fix for italian language #2046 ?

Thanks
Mirko

### CODE REVIEW

**Comment by FranckyC** [comment]
Hi @mirkodesimone7, not sure what this PR is about. Is this a more of a question?

**Comment by mirkodesimone7** [comment]
Hi @FranckyC, this is a request.
is it possbile?

**Comment by FranckyC** [comment]
@mirkodesimone7 this would be part of the next release this month. Thanks

**Comment by mirkodesimone7** [comment]
@FranckyC many Thanks!

**Pull request closed without merging**
