### PR TITLE
Using KQl to filter search results in microsoft search

### PR DESCRIPTION
**Pull request by akshataggrwal**
Using KQL to filter search results while using microsoft search instead of aggregation filters.

Issue Reference - https://github.com/microsoft-search/pnp-modern-search/issues/3934

### CODE REVIEW

**Comment by wobba** [comment]
I think we should still send as FQL, but add multiple rows with one row per each. At least for the AND clause. And a PR which comments out lines of code is not good.

**Comment by wobba** [comment]
Created #4090 which also support dates in KQL. I simplified and use `..` for date ranges, which means GE and LT for start and end date.

**Comment by akshataggrwal** [comment]
Hi @wobba - Thanks for the updates. I tested the changes in your [PR(4090)](https://github.com/microsoft-search/pnp-modern-search/pull/4090) locally for 'externalItem' entity type and it is working as expected.

Is it reasonable to assume for this to available in next release?

**Comment by wobba** [comment]
Thank you for test @akshataggrwal. I'll merge it and get a release going.

**Pull request closed without merging**
