### PR TITLE
Allows to specify the result source by name

### PR DESCRIPTION
**Pull request by luismanez**
This PR allows to configure the Search Results webpart setting the Result source by name, using the format: _Source level|Source Name_ (idea taken from the Search Query tool from @wobba).

@FranckyC / @wobba would be good if someone in the team can review the _ResultSourceIdDescription_ translations to French and Dutch :)

### CODE REVIEW

**Comment by wobba** [comment]
Thank you @luismanez and a good one :)

**Comment by FranckyC** [comment]
Thanks @luismanez that was quick ;). I'll review this when have time this week. Thanks again.

**Comment by wobba** [comment]
@luismanez Can you resolve merge conflicts due me adding a fix for the dynamic data issue.

**Comment by luismanez** [comment]
should be fine now @wobba

**Pull request merged**
