### PR TITLE
Filter Checkbox refiner options by name

### PR DESCRIPTION
**Pull request by joelfmrodrigues**
Added text box to allow filtering list of refiner options by name. This is very useful when the list of refiner options is large (i.e. 100 options).
The text box is only visible when there are more than 10 refiner options.

image

When checkbox group is set to multi-select, filter ignores selected items and those are always visible

image

### CODE REVIEW

**Comment by wobba** [comment]
Is there a web part setting to toggle filter on/off, and update docs as well to include the new filter. And great addition 👍

**Comment by joelfmrodrigues** [comment]
Just a bit flooded with work at the moment and had to swap some priorities...will look into this in a few days :)

**Comment by joelfmrodrigues** [comment]
@wobba just updated the PR. I noticed that I ended up making multiple commits so let me know if this is a problem and I will squash them

**Comment by FranckyC** [comment]
Hi @joelfmrodrigues, after a quick test, it seems there are some issues with the toggle state:

filters

**Comment by joelfmrodrigues** [comment]
Thanks @FranckyC I haven't noticed that before.
Will have a look

**Comment by joelfmrodrigues** [comment]
@FranckyC just pushed a new commit that should resolve this. I was not passing the correct property instance to TemplateRenderer from Vertical and LinkPanel.
I must been sleeping when tested that as it was behaving opposite to the expected :)

**Comment by wobba** [comment]
@joelfmrodrigues could you please update and resolve with current code?

**Comment by joelfmrodrigues** [comment]
@wobba I thought this PR was abandoned as Frank merged a PR from another user to add similar functionality.
@FranckyC please shout if I'm wrong, but I think that the other PR was only missing the option to keep selection always visible while filtering multi selects. I am still planning to implement that at some point if not done already, just delayed by other work

**Comment by wobba** [comment]
You are right 🙂

**Pull request closed without merging**
