### PR TITLE
Support for previews of aspx files 

### PR DESCRIPTION
**Pull request by gszdev**
added .gitignore file at repository level

### CODE REVIEW

**Comment by wobba** [comment]
Can you remove gitignore from the commit and also don't change the version number. v4.1 is the next to be released.

**Comment by gszdev** [comment]
Sorry. I'll close this pull request and I'll create a new one.

**Comment by wobba** [comment]
You know you can push updates to your branch while the PR is open right? No need to create a new one :)

**Comment by gszdev** [comment]
Yes, thanks.
But it was easier and faster to clean up my local folder and create new clean branch and PR. 
There were a lot of changes since my last PR in 2020. So I had a lot of files in folders like search-extensibility-library, search-custom-renderer, ... . 
Without the .gitignore file I had more than 5000 changes :anguished:.
So I don't want add any files by accident. :smirk:

**Pull request closed without merging**
