### PR TITLE
Create de-de.js / German language

### PR DESCRIPTION
**Pull request by dominiqueborer**
Added German to the repo

### CODE REVIEW

**Comment by wobba** [comment]
We will process some other PR's first. When those are done more labels will be in which has to be translated. I'll ping here once they are merged and you should update.

**Comment by wobba** [comment]
Feel free to update this one now.

**Comment by FranckyC** [comment]
@dominiqueborer can you update all localization files please so we could process your PR? Thanks!

**Comment by Coligor** [comment]
Not sure if this needs a sperate PR now, but I can translate **nl-nl.js** for the search refiners or elsewhere
Just need a heads up which file(s) to translate and to deliver to whom.

**Comment by dominiqueborer** [comment]
> @dominiqueborer can you update all localization files please so we could process your PR? Thanks!

Will do so in 2 weeks, I'm currently on vacation.

**Comment by wobba** [comment]
> Not sure if this needs a sperate PR now, but I can translate **nl-nl.js** for the search refiners or elsewhere Just need a heads up which file(s) to translate and to deliver to whom.

We already have nl-nl.

**Comment by FranckyC** [comment]
@dominiqueborer covered by @edarroudi in #1987 based on your original file. Thanks!

**Pull request closed without merging**
