### PR TITLE
Custom query suggestions

### PR DESCRIPTION
**Pull request by bschlintz**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | n/a

#### What's in this Pull Request?

Add support for custom query suggestion providers via extensibility library. This capability allows developers to write their own suggestion providers that return custom and "zero query" suggestions.

Includes the following:
- Updated extensibility library project and docs to demonstrate custom suggestion provider capabilities
- Added 'Configure Suggestions' button to search box web part settings pane that displays when there are custom suggestion providers available
  - Toggle each suggestion provider ON or OFF
- Suggestions switched from strings to ISuggestion objects
  - Added optional description text that displays on the right side of the suggestion
  - Added optional hover text that displays as a tooltip on the suggestion
  - Added optional suggestion group (default group called 'Recommended')
  - Added optional target URL to directly launch a suggestion from the search box
  - Added optional suggestion icon
  - Added optional callback when a particular suggestion is selected/clicked
- Converted built-in SharePoint suggestions to adhere to new provider interface
- Added debounce logic on the search box to limit extra calls going to suggestion providers as the user is typing quickly
- Added support for "zero query" suggestions when the search box has focus without any input

### CODE REVIEW

**Comment by FranckyC** [comment]
Hi @bschlintz .It looks great! Unfortunately, I can't review it right now due to christmas holidays. This will be proceed early January. Thanks again for your contribution!

**Comment by bschlintz** [comment]
@FranckyC - No problem at all, Happy Holidays!

**Comment by bschlintz** [comment]
@FranckyC - I've uncovered a few bugs with this PR and would advise holding the merge for now. 

The issues I'm finding are related to the way the Downshift component works, particularly the focus/blur, key up/down and highlighting/selection. Any opposition to moving away from this component in favor of using a combination of OUIF controls?

**Comment by FranckyC** [comment]
@bschlintz What components are you planning to use to replace Downshift?

**Comment by bschlintz** [comment]
@FranckyC I switched over to [FocusZone](https://developer.microsoft.com/en-us/fabric#/controls/web/focuszone) and [SearchBox](https://developer.microsoft.com/en-us/fabric#/controls/web/searchbox) instead of downshift. I pushed more updates and have been testing for awhile this morning. I think I have the kinks worked out now. When you have time, please review the code and test. The PnP Extensibility Library component has been updated with sample suggestion providers for testing as well.

**Comment by FranckyC** [comment]
Hi @bschlintz, FYI I will probably process your PR this week. Sorry for the delay.

**Comment by bschlintz** [comment]
@FranckyC We found a couple subtle UX items with the new OUIF search box that we'd like to get in this PR. Please review when you have time but don't merge until the two items below are in. Will work on getting another commit in this week.

- On initial page load, unable to press the down/up arrow key to get to the suggestions, however non-first load works normally.
- Want to add a Search button for folks that are used to typing in a search term and then clicking a button to search. This will match the behavior of the native suite bar search box in SPO.

**Comment by bschlintz** [comment]
@FranckyC I think we're _finally_ finished making updates to this PR. :-) Please let me know if you have any questions or find any issues when you have a chance to review. 

We are planning a second PR for custom query suggestions later to add additional features.

**Comment by FranckyC** [comment]
@bschlintz What a job you did ;-)! The result is pretty impressive. Very nice use of the extensibility library. @VesaJuvonen this should be demonstrated in a community call for sure if you have available spots.

**Comment by VesaJuvonen** [comment]
Hi @FranckyC - We have SP Search Web Part improvements scheduled for the 16th of January as you the presenter. Next free spot would be then in 12th of March, if we want to schedule this as a  separate demo. Absolutely open for it, if we don't have time to cover it on the 16th.

Great work @bschlintz on this and I really really like to see also internal MSFT community being more and more active on these topics as the whole PnP actually originates from MS Services... so great work on this.

**Comment by FranckyC** [comment]
I think I have only 15 minutes for this call to present the new extensibility concept. Since it is directly related, @bschlintz, do you think you could present the custom suggestions feature as well during this call?

**Comment by VesaJuvonen** [comment]
We only have 2 demos in this call - one is for max 15 min and then your updates, so you can have up to 20-25 min demo time for the search web part updates.

**Comment by FranckyC** [comment]
Ok perfect, if @bschlintz you're up, you can demo this as well. Let us know ;)

**Comment by bschlintz** [comment]
Thank you, @FranckyC - I'm game to co-present :-) I am happy to talk about the suggestion providers as part of the extensibility library if you want to introduce the main concept. Are you available for a short call this week ahead of the demo to align on presentation logistics?

@VesaJuvonen - thank you! I look forward to more as we build some of our internal offerings on top of open source projects like PnP Modern Search!

**Comment by FranckyC** [comment]
Ok nice! I'm only available today unfortunately (franck.cornu@aequos.ca if you need to send me a meeting) but no stress, just present what you did. I will start with the web component stuff and then you go for custom suggestions.

**Comment by bschlintz** [comment]
@FranckyC sounds like a plan! :-)

**Comment by VesaJuvonen** [comment]
Sounds great, thanks @bschlintz  for volunteering, really appreciated.

**Pull request merged**
