### PR TITLE
Added Finnish translations for texts that are visible to end-users

### PR DESCRIPTION
**Pull request by LauraKokkarinen**
Added Finnish translations for texts that are visible to end-users (configuration texts are clearer in English).

### CODE REVIEW

**Comment by LauraKokkarinen** [comment]
OK, I've asked @KatjaJokisalo to translate the remaining texts. We'll get back to you when all the translations have been done.

**Comment by FranckyC** [comment]
@LauraKokkarinen can we merge? Is it done? ;) Thanks!

**Comment by LauraKokkarinen** [comment]
> @LauraKokkarinen can we merge? Is it done? ;) Thanks!

Nope

**Comment by FranckyC** [comment]
@LauraKokkarinen Should we close it or this will be updated soon? Thanks!

**Comment by LauraKokkarinen** [comment]
@FranckyC and @wobba , I've now added the remaining Finnish translations.

**Comment by wobba** [comment]
Thank you 🙂

**Pull request merged**
