### PR TITLE
Wobba/v4 fixes

### PR DESCRIPTION
**Pull request by wobba**

### CODE REVIEW

**Comment by FranckyC** [comment]
Thanks @wobba, all good with SPFx 1.12.1? Did you tests with all Web Parts?

**Comment by wobba** [comment]
I'm in the process..... so don't merge yet :)

**Comment by wobba** [comment]
Cannot see any weird things.. tested on existing page and upgraded to this one. Should be good to merge this, and now I can use node v12 for everything :)

**Comment by wobba** [comment]
I think this should be good to merge in dev, and then work on additional things before a new release. Haven't noticed any issues.

**Pull request merged**
