### PR TITLE
New Functionality: Custom CSS Templates in Filter Web Part

### PR DESCRIPTION
**Pull request by MakingThingsWorkToronto**
Added custom CSS skins in searchRefiners.  Support for themeVariant in CSS using handlebars.  Minor refactoring to share logic with Search Results web part.

Added translations to loc files however used machine translation so may require update by native tongue.

Updated documentation with instructions & example skins.

### CODE REVIEW

**Comment by wobba** [comment]
Would it make sense to have a screenshow showing how the sample CSS would look?

**Comment by MakingThingsWorkToronto** [comment]
You thinking a screen shot per example?

**Comment by wobba** [comment]
One sample one should do imo.

**Comment by MakingThingsWorkToronto** [comment]
Added screenshots! Fixed a minor bug.

**Pull request closed without merging**
