### PR TITLE
Fix for multi-value tokens

### LINKED ISSUE #656: V4 Search KQL token translation
**Version used**
Version 4.0.0

**Describe the bug**
This bug is related to the KQL. I use a token in the query and is converted correctly. The token I use is {|ManagedProperty:{Page.<ColumnName>.TermID}}. The column is a managed metadata column with multiple values. The values are converted correctly and are shown in the "queryModification". (Screenshot) 

The problem is the syntax. The OR is missing in the query. 
((refinablestring05:\"10660250-3e41-469d-8d81-1787b6d0e3f0 02fda817-ebe3-4a0c-aba2-0958d79294d2 43fe9538-9f93-48f4-9c46-366f5a9cddcb\")) 

This should be:
((Refinablestring05:#010660250-3e41-469d-8d81-1787b6d0e3f0) OR (Refinablestring05:#002fda817-ebe3-4a0c-aba2-0958d79294d2) OR (Refinablestring05:#043fe9538-9f93-48f4-9c46-366f5a9cddcb))

**To Reproduce**
1. Create a column on a SitePage library. Type: Managed Metadata, multi value
2.Create a Managed property from that column (in my case refinablestring05)
3.Use the search results webpart with the above query to get the results
4. See the about without the OR function

**Expected behavior**
The problem is the syntax. The OR is missing in the query. 
((refinablestring05:\"10660250-3e41-469d-8d81-1787b6d0e3f0 02fda817-ebe3-4a0c-aba2-0958d79294d2 43fe9538-9f93-48f4-9c46-366f5a9cddcb\")) 

This should be:
((Refinablestring05:#010660250-3e41-469d-8d81-1787b6d0e3f0) OR (Refinablestring05:#002fda817-ebe3-4a0c-aba2-0958d79294d2) OR (Refinablestring05:#043fe9538-9f93-48f4-9c46-366f5a9cddcb))

**Screenshots**
screenshotSearchRestults
appcatalog

**Desktop (please complete the following information):**
 - Windows 10 build 20H2
 - Edge 87.0.664.75 
 - SharePoint Online
 - Pnp-Modern Search webpart 4.0.0 (Screenshot)

### PR DESCRIPTION
**Pull request by wobba**
Fixed #656 

Fix for {|} syntax and multiple values in a token
Fix multi term tokens to enclose with quotes.

### CODE REVIEW

**Review by FranckyC — COMMENTED** [review]
I agree on the overall resolution but not in the implementation actually. The `Object.byPath` method should return the value "as is" even if it is an array. The default `toString` method will output the values separated by a comma by default. In this case, why not saying, by convention, all multi values for the "|" operator should be separated by a comma. This is easier to follow instead of adding uncessary complexity to the `byPath` method  in my opinion. I have a fix ready if you want.

Also, the quotes encoding should occur in the `replaceOrOperator` method itself during conditions building.

**Comment by robegoja** [comment]
@FranckyC is that fix going to be available soon?

**Comment by FranckyC** [comment]
Hi @robegoja , it will be available next release so probably end of the month. If you want, you can still generate you own packages with the develop branch.

**Comment by robegoja** [comment]
Awesine @FranckyC .  I was debugging the last github version and I saw that it is breaking up and putting OR.  However I notice one little thing the first value it took in for the metadata label it has a leading space for the first 
value (RefinableString100: " FirstValue") OR (RefinableString100: "Second Value"). When you are publishing can you please checked on that leading space I saw in the resulting output.

**Comment by wobba** [comment]
Good catch @robegoja as spaces in property queries, specially around : breaks the parsing.

**Pull request closed without merging**
