### PR TITLE
Dropped out Package JSON - and - included decodeURIComponent

### PR DESCRIPTION
**Pull request by kachihro**
Sorry for the mix-up in branches - let me know if anything else to cover

### CODE REVIEW

**Comment by wobba** [comment]
There's a merge conflict. You need to pull down the latest dev branch and resolve your PR branch.

**Comment by kachihro** [comment]
I can't work out how to resolve the conflicts - I'm using Visual Studio for Git merge - but it's not showing conflicts.   And - I pulled the code from DEV - and compared and did a code update against the DEVELOP branch - still shows an error.

**Comment by kachihro** [comment]
I can re-do as a new fork perhaps - off the DEVELOP branch - and then delete this PR

**Comment by wobba** [comment]
If you do the steps below you should be able to figure it out. If not, re-implement your change with a new PR. I know merging can be tricky at times.

```
git checkout developer
git pull
git checkout <your feature branch>
git merge developer
```

**Comment by wobba** [comment]
..and you don't need a new PR for every change.. you can update on which ever you have as long as you push on the PR's branch :)

**Comment by kachihro** [comment]
Sorted it out !    I hadn't done a branch merge from a FORK'ed repo.   Needed to do "git fetch upsteam' - and then 'git merge upstream/develop'

**Comment by kachihro** [comment]
> ..and you don't need a new PR for every change.. you can update on which ever you have as long as you push on the PR's branch :)

Yep - I did the first branch off master - not develop.    This is only the 2nd time I've done a GitHub update / PNP

**Comment by wobba** [comment]
I improved/simplified the code in the dev branch to cover all user environment scenarios. Thank you for the inspiration and we'll give credit :)

**Pull request closed without merging**
