### PR TITLE
[Bugfix] Revert to first page when search refiner value is selected

### PR DESCRIPTION
**Pull request by LeemansBE**
Hi,

There is a minor bug when you have searchresults with paging and search refiners enabled.
When you browse to the next page and apply a refinement filter the search results will become messed up.

This pull request will revert the search results back to the first page when a search refiner is applied.

Could you guys have a look? 😃 

Thx!
Bart

### CODE REVIEW

**Comment by LeemansBE** [comment]
Fix for bug https://github.com/microsoft-search/pnp-modern-search/issues/332

**Comment by xichro** [comment]
+1 Same issue.

**Comment by wobba** [comment]
Thank you :)

**Comment by wobba** [comment]
@LeemansBE I'm seeing an issue with refiners and verticals. If I pick a refiner on `Vertical 1`, then switch to `Vertical 2`. Then that looks good with refiners reset. If I switch back to `Vertical 1` then the first chosen refiner is applied, but not selected. Ideally a vertical switch should reset refiners and clear all state. I'm wondering if we need a connection between vertical and refiner web part, or if we can sort of work around it.

**Comment by wobba** [comment]
Fixed with #424

**Pull request merged**
