### PR TITLE
[Search Results] Added sort control

### PR DESCRIPTION
**Pull request by FranckyC**
Added a sort control component to layouts:
- Now the list of sortable properties is a static list of 'Sortable' managed properties in the search schema. Custom properties or `RefinableXXX` have to be entered manually.
- Updated the Details List sort behavior. Now there is no static sorting anymore. The field used to sort a column comes from the data source sort settings configuration and we clearly make the distinction between display value and sort value in the configuration.

### CODE REVIEW

**Comment by FranckyC** [comment]
@wobba if you have time to test this one.

**Comment by wobba** [comment]
I didn't find any issues right away when testing so I merged it. Would be good to have more people test it out as well.

**Comment by ellinge** [comment]
You forgot to bump @pnp/modern-search-extensibility, getting errors on gulp build without it

**Comment by FranckyC** [comment]
@ellinge nope, the pre-release is in the [release/4.6.0](https://github.com/microsoft-search/pnp-modern-search/tree/release/4.6.0) branch, not `develop`. Try to use this one and let me know.

**Pull request merged**
